//alert
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const SET_MODAL_CONTENT = "SET_MODAL_CONTENT";
//auth
export const AUTH_START = "AUTH_START";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_CHECK_STATE = "AUTH_CHECK_STATE";
export const AUTH_CHECK_STATE_START = "AUTH_CHECK_STATE_START";
export const AUTH_CHECK_STATE_FINISH = "AUTH_CHECK_STATE_FINISH";
export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";
export const SEND_TOKEN_PASSWORD = "SEND_TOKEN_PASSWORD";
export const SEND_TOKEN_PASSWORD_SUCCESS = "SEND_TOKEN_PASSWORD_SUCCESS";
export const CHECK_TOKEN_PASSWORD = "CHECK_TOKEN_PASSWORD";
export const CHECK_TOKEN_PASSWORD_SUCCESS = "CHECK_TOKEN_PASSWORD_SUCCESS";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const LOGOUT = "LOGOUT";
//theme
export const SET_THEME = "SET_THEME";
//nav
export const SET_MENU = "SET_MENU";
export const SET_SUBMENU = "SET_SUBMENU";
//users
export const USER_START = "USER_START";
export const USER_FAIL = "USER_FAIL";
export const FETCH_USERS = "FETCH_USERS";
export const FETCH_MEMBERS = "FETCH_MEMBERS";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const DELETE_MULTIPLE_USERS = "DELETE_MULTIPLE_USERS";
export const DELETE_MULTIPLE_USERS_SUCCESS = "DELETE_MULTIPLE_USERS_SUCCESS";
export const ADD_USER = "ADD_USER";
export const UPDATE_USER = "UPDATE_USER";
export const SET_NEW_PASSWORD = "SET_NEW_PASSWORD";
export const FORM_USER_SUCCESS = "FORM_USER_SUCCESS";
//profile
export const FETCH_EDUCATIONS = "FETCH_EDUCATIONS";
export const FETCH_EDUCATIONS_SUCCESS = "FETCH_EDUCATIONS_SUCCESS";
export const FETCH_EDUCATION = "FETCH_EDUCATION";
export const ADD_EDUCATION = "ADD_EDUCATION";
export const UPDATE_EDUCATION = "UPDATE_EDUCATION";
export const DELETE_EDUCATION = "DELETE_EDUCATION";
export const FETCH_EXPERIENCES = "FETCH_EXPERIENCES";
export const FETCH_EXPERIENCES_SUCCESS = "FETCH_EXPERIENCES_SUCCESS";
export const FETCH_EXPERIENCE = "FETCH_EXPERIENCE";
export const ADD_EXPERIENCE = "ADD_EXPERIENCE";
export const UPDATE_EXPERIENCE = "UPDATE_EXPERIENCE";
export const DELETE_EXPERIENCE = "DELETE_EXPERIENCE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
//categories
export const CATEGORIES_START = "CATEGORIES_START";
export const CATEGORIES_FAIL = "CATEGORIES_FAIL";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const ADD_CATEGORIES = "ADD_CATEGORIES";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const FORM_CATEGORIES_SUCCESS = "FORM_CATEGORIES_SUCCESS";
export const DELETE_MULTIPLE_CATEGORIES = "DELETE_MULTIPLE_CATEGORIES";
export const DELETE_MULTIPLE_CATEGORIES_SUCCESS =
  "DELETE_MULTIPLE_CATEGORIES_SUCCESS";
export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
//jobs
export const ADD_JOBS = "ADD_JOBS";
export const JOBS_START = "JOBS_START";
export const JOBS_FAIL = "JOBS_FAIL";
export const FORM_JOBS_SUCCESS = "FORM_JOBS_SUCCESS";
export const FETCH_JOBS = "FETCH_JOBS";
export const FETCH_JOBS_SUCCESS = "FETCH_JOBS_SUCCESS";
export const DELETE_JOB = "DELETE_JOB";
export const DELETE_JOB_SUCCESS = "DELETE_JOB_SUCCESS";
export const FETCH_JOB = "FETCH_JOB";
export const FETCH_JOB_SUCCESS = "FETCH_JOB_SUCCESS";
export const UPDATE_JOBS = "UPDATE_JOBS";
export const FETCH_ME = "FETCH_ME";
export const FETCH_COUNT_JOB = "FETCH_COUNT_JOB";
export const FETCH_COUNT_JOB_SUCCESS = "FETCH_COUNT_JOB_SUCCESS";
export const APPLY_JOB_SUCCESS = "APPLY_JOB_SUCCESS";
